# Login Dataset Analysis

This is a sample analysis for the login dataset which I have generated using ChatGPT for learning basic cybersecurity + data analysis work.

## Importing Relevant Libraries and Dataset

In [57]:
import pandas as pd
df = pd.read_csv('login_dataset.csv')

## Basic EDA

My goal here is to read the csv file and to see what I am working on.

In [58]:
df.describe()

           timestamp username ip_address   status
count           3200     3200       3200     3200
unique          1267       20         51        2
top     1/1/26 10:01    user1  10.0.0.99  success
freq              64      208        200     2541

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   timestamp   3200 non-null   object
 1   username    3200 non-null   object
 2   ip_address  3200 non-null   object
 3   status      3200 non-null   object
dtypes: object(4)
memory usage: 100.1+ KB

In [60]:
df.head()

      timestamp username    ip_address   status
0  1/1/26 04:32   user20  192.168.1.22  success
1  1/1/26 01:01   user20   192.168.1.4   failed
2  1/1/26 15:07   user10  192.168.1.30  success
3  1/1/26 05:02    user2  192.168.1.39  success
4  1/1/26 11:09    user8  192.168.1.26  success

## Data Transformation

### Converting <code>Timestamp</code> column into a datetime format, and separating them into date and time columns.

This allows us to group the data later on in the later sections.

In [61]:
df['date and time'] = pd.to_datetime(df['timestamp'])

/var/folders/84/g4hy0l0d54ndr4rmqsrt94d80000gn/T/ipykernel_96648/3358383140.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date and time'] = pd.to_datetime(df['timestamp'])

In [62]:
df.head(3)

      timestamp username    ip_address   status       date and time
0  1/1/26 04:32   user20  192.168.1.22  success 2026-01-01 04:32:00
1  1/1/26 01:01   user20   192.168.1.4   failed 2026-01-01 01:01:00
2  1/1/26 15:07   user10  192.168.1.30  success 2026-01-01 15:07:00

## Basic Data Analysis

Part 1: Finding how many failed login attempts are done for each user.

In [63]:
attempts_df = df.groupby(['username', 'status']).size().reset_index(name = 'Attempt Count')

In [64]:
attempts_df[attempts_df['status'] == 'failed'].sort_values(by = 'Attempt Count', ascending = False)

   username  status  Attempt Count
30    user5  failed             72
0     user1  failed             69
26    user3  failed             61
28    user4  failed             57
22    user2  failed             49
20   user19  failed             31
36    user8  failed             30
32    user6  failed             29
12   user15  failed             27
14   user16  failed             26
18   user18  failed             24
24   user20  failed             23
8    user13  failed             23
4    user11  failed             22
38    user9  failed             22
6    user12  failed             21
16   user17  failed             20
2    user10  failed             20
10   user14  failed             19
34    user7  failed             14

Part 2: Isolating the top five entries on the dataset and grouping them by IP addresses trying to login.

In [65]:
first_five_df = df[df['username'].isin(['user5', 'user1', 'user3', 'user4', 'user2'])]

In [66]:
first_five_df.groupby(['ip_address', 'username']).size().reset_index(name = 'Login Attempts')

      ip_address username  Login Attempts
0      10.0.0.99    user1              42
1      10.0.0.99    user2              30
2      10.0.0.99    user3              39
3      10.0.0.99    user4              43
4      10.0.0.99    user5              46
..           ...      ...             ...
241  192.168.1.9    user1               3
242  192.168.1.9    user2               6
243  192.168.1.9    user3               6
244  192.168.1.9    user4               4
245  192.168.1.9    user5               5

[246 rows x 3 columns]

Part 3: Investigating <code>ip_address == '10.0.0.99'</code> for any successful login.

In [67]:
df[(df['ip_address'] == '10.0.0.99') & (df['status'] == 'success')]

Empty DataFrame
Columns: [timestamp, username, ip_address, status, date and time]
Index: []